### ISSUE TITLE
The links in the readme.md to the Windows CommunityToolkit API docs are all broken

### ISSUE THREAD

**Issue by jevansaks** [microsoftgraph/uwp-csharp-controls-sample#2]
They link to things like https://docs.microsoft.com/en-us/windows/communitytoolkit/graph/profilecard which aren't there.

**Comment by jasonjoh** [comment]
Thanks for your interest in Microsoft Graph! We are archiving this sample, so I'm closing this issue. For a replacement UWP app sample, please see https://github.com/microsoftgraph/msgraph-training-uwp. We apologize for any inconvenience.

The Graph components of the toolkit were migrated out to a separate package here: https://github.com/windows-toolkit/Graph-Controls
